import {Router} from "express";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import User from "../models/User.js";
import {auth} from "../middleware/auth.js";
const r=Router();
const token=u=>jwt.sign({id:u._id,role:u.role},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||"7d"});
r.post("/register",async(req,res,next)=>{try{const {name,password}=req.body; const email=String(req.body.email||"").trim().toLowerCase(); if(!name||!email||!password)return res.status(400).json({message:"Name, email and password are required"});if(await User.findOne({email}))return res.status(409).json({message:"Email already registered"});const u=await User.create({name,email,password:await bcrypt.hash(password,12)});res.status(201).json({token:token(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})}catch(e){next(e)}});
r.post("/login",async(req,res,next)=>{try{const email=String(req.body.email||"").trim().toLowerCase(); const u=await User.findOne({email}).select("+password");if(!u||!(await bcrypt.compare(req.body.password,u.password)))return res.status(401).json({message:"Invalid email or password"});res.json({token:token(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})}catch(e){next(e)}});
r.get("/me",auth,async(req,res)=>res.json({user:req.user}));
r.post("/logout",(req,res)=>res.json({message:"Logged out"}));
export default r;
