import "dotenv/config";
import express from "express";
import cors from "cors";
import morgan from "morgan";
import mongoose from "mongoose";
import authRoutes from "./routes/auth.routes.js";
import courseRoutes from "./routes/course.routes.js";
import enrollmentRoutes from "./routes/enrollment.routes.js";
import progressRoutes from "./routes/progress.routes.js";
import reviewRoutes from "./routes/review.routes.js";
import quizRoutes from "./routes/quiz.routes.js";
import certificateRoutes from "./routes/certificate.routes.js";
import wishlistRoutes from "./routes/wishlist.routes.js";

const app=express();
app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:5173"}));
app.use(express.json({limit:"2mb"}));
app.use(morgan("dev"));
app.get("/api/health",(req,res)=>res.json({ok:true,service:"LearnHub API"}));
app.use("/api/auth",authRoutes);
app.use("/api/courses",courseRoutes);
app.use("/api/enrollments",enrollmentRoutes);
app.use("/api/progress",progressRoutes);
app.use("/api/reviews",reviewRoutes);
app.use("/api/quizzes",quizRoutes);
app.use("/api/certificates",certificateRoutes);
app.use("/api/wishlist",wishlistRoutes);
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({message:err.message||"Server error"});});
const port=process.env.PORT||5000;
mongoose.connect(process.env.MONGO_URI||"mongodb://127.0.0.1:27017/learnhub").then(()=>app.listen(port,()=>console.log(`LearnHub API running on ${port}`))).catch(err=>{console.error("MongoDB connection failed:",err.message);process.exit(1)});
