import { useEffect,useState } from "react";
import { useParams } from "react-router-dom";
import { CheckCircle2, ChevronLeft, ChevronRight, Menu } from "lucide-react";
import api from "../services/api";

export default function LearnPage(){
 const {id}=useParams(); const [course,setCourse]=useState(null),[active,setActive]=useState(null),[done,setDone]=useState([]);
 useEffect(()=>{api.get(`/courses/${id}`).then(r=>{setCourse(r.data.course);setActive(r.data.course.modules?.[0]?.lessons?.[0])});api.get(`/progress/${id}`).then(r=>setDone(r.data.progress?.completedLessons||[])).catch(()=>{});},[id]);
 if(!course)return <div className="p-10">Loading course...</div>;
 const lessons=course.modules?.flatMap(m=>m.lessons||[])||[], index=lessons.findIndex(x=>x._id===active?._id);
 const mark=async()=>{if(!active)return;await api.put(`/progress/${id}`,{lessonId:active._id,completed:true});setDone([...done,active._id])};
 return <div className="min-h-screen bg-slate-950 text-white"><header className="flex h-16 items-center border-b border-slate-800 px-4"><a href="/" className="font-black">Learn<span className="text-emerald-400">Hub</span></a><span className="mx-4 text-slate-600">/</span><span className="truncate text-sm">{course.title}</span></header>
 <div className="grid min-h-[calc(100vh-64px)] lg:grid-cols-[280px_1fr_250px]">
  <aside className="hidden border-r border-slate-800 p-4 lg:block"><div className="mb-5 flex items-center gap-2 font-bold"><Menu size={18}/>Course content</div>{course.modules?.map(m=><div key={m._id} className="mb-5"><p className="mb-2 text-xs font-bold uppercase tracking-widest text-slate-500">{m.title}</p>{m.lessons?.map(l=><button onClick={()=>setActive(l)} key={l._id} className={`flex w-full items-center gap-2 rounded-lg p-2 text-left text-sm ${active?._id===l._id?"bg-slate-800 text-emerald-300":"text-slate-400"}`}><CheckCircle2 size={15} className={done.includes(l._id)?"text-emerald-400":"text-slate-600"}/>{l.title}</button>)}</div>)}</aside>
  <main className="flex flex-col"><div className="aspect-video bg-black p-6 md:p-10"><div className="grid h-full place-items-center rounded-2xl bg-slate-900 text-center"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-500 text-xl">▶</div><p className="mt-4 text-slate-400">Video lesson placeholder</p></div></div></div><div className="mx-auto w-full max-w-4xl flex-1 p-6 md:p-10"><p className="text-sm text-emerald-400">Lesson {index+1} of {lessons.length}</p><h1 className="mt-2 text-3xl font-black">{active?.title}</h1><p className="mt-6 leading-8 text-slate-300">{active?.content||"Welcome to this lesson. Work through the material, complete the practical exercise and mark the lesson complete when you're ready."}</p><div className="mt-10 flex justify-between"><button className="btn-secondary !border-slate-700 !bg-transparent !text-white" disabled={index<=0} onClick={()=>setActive(lessons[index-1])}><ChevronLeft/>Previous</button><div className="flex gap-2"><button onClick={mark} className="btn-primary">{done.includes(active?._id)?"Completed":"Mark complete"}</button><button className="btn-primary" disabled={index>=lessons.length-1} onClick={()=>setActive(lessons[index+1])}>Next<ChevronRight/></button></div></div></div></main>
  <aside className="hidden border-l border-slate-800 p-6 lg:block"><p className="text-xs uppercase tracking-widest text-slate-500">Your progress</p><div className="mt-4 text-4xl font-black">{Math.round(done.length/Math.max(lessons.length,1)*100)}%</div><div className="mt-4 h-2 rounded-full bg-slate-800"><div className="h-2 rounded-full bg-emerald-400" style={{width:`${done.length/Math.max(lessons.length,1)*100}%`}}/></div><p className="mt-4 text-sm text-slate-400">{done.length} of {lessons.length} lessons completed.</p></aside>
 </div></div>
}
